<!DOCTYPE html>
<html lang="en">
<head>
<title>CSS Template</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Calibri Light, serif;
  font-size: medium;
}
</style>
</head>
<body>
<h1 align="center"><span style="font-size: x-large;"><strong>My Roommate</strong></h1>
<br>
<p>Hi <strong>${fullName}</strong>,</p>
<p>Forgot your password? We have sent you a new password for your account.</p>
<p>This is your new password: <strong>${password}</strong></p>
<p>Please use the temporary password we provided to log in, then change your password. <a href="#">Click here</a></p>
<p>Best regards,</p>
</body>
</html>
